name: CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: |
          dotnet publish -c Release -o ./publish
          Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip
        shell: pwsh

      - name: Deploy
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          $publishSettingsPath = ".github/workflows/symphonix.runasp.net-WebDeploy.publishSettings"
          $publishUrl = (Select-Xml "//publishUrl" -Path $publishSettingsPath).Node.InnerText
          $username = (Select-Xml "//userName" -Path $publishSettingsPath).Node.InnerText
          $password = $env:FTP_PASSWORD
          
          # Build the destination arguments string
          $destArgs = "contentPath='Default Web Site/symphonix.runasp.net',computerName='$publishUrl',userName='$username',password='$password',authType='Basic',includeAcls='False'"
          
          # Use Start-Process to properly handle the arguments
          $process = Start-Process -FilePath "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -ArgumentList @(
              "-source:package=`"publish.zip`"",
              "-dest:$destArgs",
              "-verb:sync",
              "-enableRule:DoNotDeleteRule"
            ) `
            -NoNewWindow -Wait -PassThru
          
          if ($process.ExitCode -ne 0) {
            Write-Error "MSDeploy failed with exit code $($process.ExitCode)"
            exit $process.ExitCode
          }
