name: CI/CD to FTP (MonsterASP Safe)

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: |
          dotnet publish --configuration Release --no-restore --output ./publish -p:PublishTrimmed=true
        shell: pwsh

      - name: Deploy to temporary folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /temp_deploy/
          protocol: ftps
          exclude: |
            **/*.pdb
            **/logs/**
            **/.htaccess
            **/web.config
          dangerous-clean-slate: true

      - name: Swap folder to production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ""
          server-dir: /wwwroot/
          protocol: ftps
          dangerous-clean-slate: true
