name: CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build Blogtify.sln --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish Blogtify/Blogtify/Blogtify.csproj -c Release -o ./publish
        shell: pwsh

      - name: Deploy with MSDeploy
        shell: pwsh
        run: |
          $publishUrl = "${{ secrets.PUBLISH_URL }}"
          $siteName   = "${{ secrets.SITE_NAME }}"
          $username   = "${{ secrets.USERNAME }}"
          $password   = "${{ secrets.PASSWORD }}"
          $publishFolder = "${{ github.workspace }}\publish"

          echo "Deploying to $publishUrl, site=$siteName"

          & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -source:contentPath="$publishFolder" `
            "-dest:auto,computerName=https://$publishUrl:8172/msdeploy.axd,userName=$username,password=$password,authType=Basic,includeAcls=False" `
            -verb:sync `
            -enableRule:DoNotDeleteRule `
            "-setParam:name=IIS Web Application Name,value=$siteName"
