name: CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build Blogtify.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Blogtify/Blogtify/Blogtify.csproj -c Release -o ${{ github.workspace }}/publish
        shell: pwsh

      - name: Deploy
        shell: pwsh
        run: |
          $publishSettingsPath = ".github/workflows/symphonix.runasp.net-WebDeploy.publishSettings"
          [xml]$xml = Get-Content $publishSettingsPath
          $profile   = $xml.publishData.publishProfile
          $publishUrl = $profile.publishUrl
          $siteName   = $profile.msdeploySite
          $username   = $profile.userName
          $password   = $profile.userPWD

          echo "Deploying to $publishUrl, site=$siteName"

          & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -source:contentPath="${{ github.workspace }}/publish" `
            -dest:auto,computerName="https://$publishUrl:8172/msdeploy.axd",userName="$username",password="$password",authType=Basic,includeAcls=False,site="$siteName" `
            -verb:sync `
            -enableRule:DoNotDeleteRule
